services:
  - type: worker
    name: uzbot
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: starter
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        value: uzbot.db
